using System.Globalization;
using System.Text;
using System.Text.Json;
using Amazon.Lambda.APIGatewayEvents;
using Amazon.Lambda.Core;
using Amazon.S3;
using Amazon.S3.Model;

[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

namespace AnalyticsReportService;

public class Function
{
    private static readonly IAmazonS3 S3Client = new AmazonS3Client();

    private static readonly string BucketName =
        Environment.GetEnvironmentVariable("REPORT_BUCKET_NAME") ?? string.Empty;

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true
    };

    private static readonly JsonSerializerOptions OutputOptions = new()
    {
        WriteIndented = true
    };

    private const int LinkLifetimeHours = 12;

    public async Task<APIGatewayProxyResponse> FunctionHandler(
        APIGatewayProxyRequest request,
        ILambdaContext context)
    {
        if (string.IsNullOrWhiteSpace(BucketName))
        {
            context.Logger.LogError("REPORT_BUCKET_NAME environment variable is not set.");
            return Respond(500, new ReportResponse
            {
                Generated = false,
                Reason = "Report bucket is not configured."
            });
        }

        AnalyticsReportRequest? payload;
        try
        {
            payload = JsonSerializer.Deserialize<AnalyticsReportRequest>(
                request.Body ?? string.Empty, JsonOptions);
        }
        catch (JsonException ex)
        {
            context.Logger.LogError($"Malformed request body: {ex.Message}");
            return Respond(400, new ReportResponse
            {
                Generated = false,
                Reason = "Request body is not valid JSON."
            });
        }

        if (payload == null)
        {
            return Respond(400, new ReportResponse
            {
                Generated = false,
                Reason = "Request body is empty."
            });
        }

        string generatedAt = DateTime.UtcNow.ToString("yyyyMMdd-HHmmss", CultureInfo.InvariantCulture);
        string baseKey = $"analytics-reports/{DateTime.UtcNow:yyyy/MM/dd}/report-{generatedAt}-{Guid.NewGuid():N}";

        try
        {
            await PutObjectAsync($"{baseKey}.csv", BuildCsv(payload), "text/csv", context);
            await PutObjectAsync($"{baseKey}.json", JsonSerializer.Serialize(payload, OutputOptions),
                "application/json", context);

            string downloadUrl = await S3Client.GetPreSignedURLAsync(new GetPreSignedUrlRequest
            {
                BucketName = BucketName,
                Key = $"{baseKey}.csv",
                Expires = DateTime.UtcNow.AddHours(LinkLifetimeHours),
                Verb = HttpVerb.GET
            });

            context.Logger.LogInformation(
                $"Generated analytics report {baseKey} covering {payload.DateFrom:yyyy-MM-dd} to {payload.DateTo:yyyy-MM-dd}.");

            return Respond(200, new ReportResponse
            {
                Generated = true,
                CsvKey = $"{baseKey}.csv",
                JsonKey = $"{baseKey}.json",
                DownloadUrl = downloadUrl,
                ExpiresInHours = LinkLifetimeHours
            });
        }
        catch (AmazonS3Exception ex)
        {
            context.Logger.LogError($"S3 write failed: {ex.Message}");
            return Respond(502, new ReportResponse
            {
                Generated = false,
                Reason = "Report could not be written to storage."
            });
        }
    }

    private static async Task PutObjectAsync(string key, string content, string contentType, ILambdaContext context)
    {
        await S3Client.PutObjectAsync(new PutObjectRequest
        {
            BucketName = BucketName,
            Key = key,
            ContentBody = content,
            ContentType = contentType
        });

        context.Logger.LogInformation($"Wrote s3://{BucketName}/{key}");
    }

    private static string BuildCsv(AnalyticsReportRequest payload)
    {
        var sb = new StringBuilder();

        sb.AppendLine("Job & Career Platform - Analytics Report");
        sb.AppendLine($"Reporting period,{payload.DateFrom:yyyy-MM-dd},{payload.DateTo:yyyy-MM-dd}");
        sb.AppendLine($"Generated (UTC),{DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}");

        if (!string.IsNullOrWhiteSpace(payload.GeneratedBy))
        {
            sb.AppendLine($"Generated by,{Escape(payload.GeneratedBy)}");
        }

        sb.AppendLine();
        sb.AppendLine("Summary");
        sb.AppendLine("Metric,Value");
        sb.AppendLine($"New job seekers,{payload.NewJobSeekers}");
        sb.AppendLine($"Jobs published,{payload.JobsPublished}");
        sb.AppendLine($"Applications submitted,{payload.ApplicationsSubmitted}");
        sb.AppendLine($"User activities logged,{payload.UserActivities}");

        AppendBreakdown(sb, "Jobs by category", payload.JobsByCategory);
        AppendBreakdown(sb, "Applications by status", payload.ApplicationsByStatus);
        AppendBreakdown(sb, "Top required skills", payload.TopRequiredSkills);

        return sb.ToString();
    }

    private static void AppendBreakdown(StringBuilder sb, string heading, List<ReportBreakdownItem>? items)
    {
        if (items == null || items.Count == 0)
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine(heading);
        sb.AppendLine("Label,Count");

        foreach (ReportBreakdownItem item in items)
        {
            sb.AppendLine($"{Escape(item.Label)},{item.Count}");
        }
    }

    private static string Escape(string? value)
    {
        string safe = value ?? string.Empty;

        if (safe.Contains(',') || safe.Contains('"') || safe.Contains('\n'))
        {
            return $"\"{safe.Replace("\"", "\"\"")}\"";
        }

        return safe;
    }

    private static APIGatewayProxyResponse Respond(int statusCode, ReportResponse body)
    {
        return new APIGatewayProxyResponse
        {
            StatusCode = statusCode,
            Body = JsonSerializer.Serialize(body),
            Headers = new Dictionary<string, string> { ["Content-Type"] = "application/json" }
        };
    }
}

public class AnalyticsReportRequest
{
    public DateTime DateFrom { get; set; }
    public DateTime DateTo { get; set; }
    public string? GeneratedBy { get; set; }
    public int NewJobSeekers { get; set; }
    public int JobsPublished { get; set; }
    public int ApplicationsSubmitted { get; set; }
    public int UserActivities { get; set; }
    public List<ReportBreakdownItem>? JobsByCategory { get; set; }
    public List<ReportBreakdownItem>? ApplicationsByStatus { get; set; }
    public List<ReportBreakdownItem>? TopRequiredSkills { get; set; }
}

public class ReportBreakdownItem
{
    public string Label { get; set; } = string.Empty;
    public int Count { get; set; }
}

public class ReportResponse
{
    public bool Generated { get; set; }
    public string? CsvKey { get; set; }
    public string? JsonKey { get; set; }
    public string? DownloadUrl { get; set; }
    public int ExpiresInHours { get; set; }
    public string? Reason { get; set; }
}
